Backporting the fix into 10.6 codeline for DERBY-4835 Trigger plan does not recompile with upgrade from 10.5.3.0 to 10.6.1.0 causing java.lang.NoSuchMethodError
Incremented the release number so that the code changes for upgrade path will be executed.



git-svn-id: https://svn.apache.org/repos/asf/db/derby/code/branches/10.6@1022333 13f79535-47bb-0310-9956-ffa450edef68