java/testing/org/apache/derbyTesting/functionTests/tests/jdbc4/StatementTest.java update for DERBY-2065 (587040) Network and embedded difference in SQLSTATE and message when Connection.close() with open transaction. java/testing/org/apache/derbyTesting/functionTests/tests/jdbc4/TestDbMetaData.java
update for DERBY-2983 (563172) The ResultSet returned by DatabaseMetaData.getFunctions() does not contain a required column named FUNCTION_TYPE.

java/testing/org/apache/derbyTesting/functionTests/tests/tools/ImportExportProcedureTest.java
java/testing/org/apache/derbyTesting/junit/SupportFilesSetup.java

Update for DERBY-3068 (616085)  testImportExportProcedureNegative(org.apache.derbyTesting.functionTests.tests.tools.ImportExportProcedureTest)junit.framework.ComparisonFailure: Unexpected SQL state. expected:<38000> but was:<XIE0S>



git-svn-id: https://svn.apache.org/repos/asf/db/derby/code/branches/10.3.2.1_test@639745 13f79535-47bb-0310-9956-ffa450edef68